const PRODUCTS = [
    {
        id: 1,
        name: "T-shirt with Tape Details",
        price: 120,
        oldPrice: null, // không có giảm giá thì để null
        rating: 4.5,
        image: "./img/ao_den.png",
        category: "tshirt",
    },
    {
        id: 2,
        name: "Skinny Fit Jeans",
        price: 240,
        oldPrice: 260, // có giảm giá thì mới có field này
        rating: 3.5,
        image: "./img/jean_xanh_dai.png",
        category: "jeans",
    },
    {
        id: 3,
        name: "Checkered Shirt",
        price: 180,
        oldPrice: null,
        rating: 4.5,
        image: "./img/ao_soc_do.png",
        category: "shirt",
    },
    {
        id: 4,
        name: "Sleeve Striped T-shirt",
        price: 130,
        oldPrice: 160,
        rating: 4.5,
        image: "./img/ao_soc_cam.png",
        category: "tshirt",
    },
    {
        id: 5,
        name: "Vertical Striped Shirt",
        price: 212,
        oldPrice: 232,
        rating: 4.8,
        image: "./img/ao_soc_xanh.png",
        category: "shirt",
    },
    {
        id: 6,
        name: "Courage Graphic T-shirts",
        price: 145,
        oldPrice: null,
        rating: 4.2,
        image: "./img/ao_cam.png",
        category: "tshirt",
    },
    {
        id: 7,
        name: "Loose Fit Bermuda Shorts",
        price: 80,
        oldPrice: null,
        rating: 4.0,
        image: "./img/jean_xanh_ngan.png",
        category: "shorts",
    },
    {
        id: 8,
        name: "Faded Skinny Jeans",
        price: 210, 
        oldPrice: null,
        rating: 4.9,
        image: "./img/jean_den.png",
        category: "jeans",
    }
];